version: '3.3'
services:
  db:
    container_name: 'mysql-culpeper'
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mukit
  springbwapp:
    container_name: 'culpeper'
    image: 'culpeper:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8080:443"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-culpeper:3306/culpeper?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mukit